[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_speed = 115200

lib_deps =
  esphome/AsyncTCP-esphome @ ^2.1.3
  esphome/ESPAsyncWebServer-esphome @ ^3.2.2
  bblanchon/ArduinoJson @ ^6.21.3
  tzapu/WiFiManager@^2.0.17
  knolleary/PubSubClient@^2.8


build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D MQTT_MAX_PACKET_SIZE=512
