[platformio]
default_envs = lolin_s3_mini


[env]
platform = espressif32
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_speed = 115200

lib_deps =
  esphome/AsyncTCP-esphome @ ^2.1.3
  esphome/ESPAsyncWebServer-esphome @ ^3.2.2
  bblanchon/ArduinoJson @ ^6.21.3
  tzapu/WiFiManager@^2.0.17
  knolleary/PubSubClient@^2.8


build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D MQTT_MAX_PACKET_SIZE=512
  -DHAS_BUILD_CONFIG
extra_scripts = pre:extra/build_config.py

[env:esp32]
board = esp32dev

[env:lolin_s3_mini]
board = lolin_s3_mini

upload_speed = 921600
build_flags =
  ${env.build_flags}
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D PWB_PIN_RELAY=16
  -D LED_PIN=21
  -D PWB_PIN_ADC_VBAT=1
